Controllers/WeatherDataController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Uppgift7.Models;
using Uppgift7.Models.Features.InputParser;
using Uppgift7.Data;
using System.Text.Encodings.Web;
using Microsoft.EntityFrameworkCore;
using System.Net;
using Uppgift7.Models.Features.SMHI;
using Newtonsoft.Json;
using System.Text;
using System.Net.Http;
using System.Globalization;

namespace Uppgift7.Controllers
{
    [ApiController]
    [Route("Data")]
    public class WeatherDataController : Controller
    {
        private IEnumerable<IWeatherData> _weatherDataServices;
        private IEnumerable<WeatherModel> _weatherData;
        private ISmhiApiServices _smhiApiServices;
        private IWeatherInputParser _inputParser;
        private readonly MvcWeatherContext _context;
        private string _smhiCity;

        public WeatherDataController(IEnumerable<IWeatherData> weatherDataServices, IWeatherInputParser inputParser,
                MvcWeatherContext context, ISmhiApiServices smhiApiServices)
        {
            _weatherDataServices = weatherDataServices;
            _inputParser = inputParser;
            _context = context;
            _weatherData = _inputParser.ParseWeatherInput();
            _smhiApiServices = smhiApiServices;
        }

        // Depreciated endpoint
        [HttpGet("Analyze")]
        public ActionResult<IEnumerable<WeatherModel>> GetStuff()
        {
            var result = new List<WeatherModel>();
            foreach (var service in _weatherDataServices)
            {
                result.Add(service.GetData(_weatherData));
            }
            return Ok(result);
        }
        [HttpGet("GetJson")]
        public ActionResult<IEnumerable<WeatherModel>> GetJson()
        {
            var weather = from w in _context.Weather
                          select w;
            var query = weather.OrderBy(d => d.Timestamp)
                               .Select(d => new { date = d.Date, value = d.TemperatureC });
            return Json(query);
        }
        [HttpGet("SMHI/GetCity")]
        public ActionResult<string> GetSMHIcity()
        {
            return Json(_smhiCity);
        }
        [HttpGet("SMHI/GetChart")]
        public async Task<ActionResult<IEnumerable<WeatherModel>>> GetSmhiJson(string city)
        {
            _smhiCity = city;
            var lonlat = new Cities(_smhiCity).LonLat;

            SmhiModel data = await _smhiApiServices.GetWeatherByPoint(lonlat[0], lonlat[1]);
            var chartData = _smhiApiServices.ConvertToChartJson(data);
            var query = chartData.Select(d => new { date = d.Date.ToString(), value = d.Value });
            return Json(query);
        }
        // GET: Data
        public IActionResult Index()
        {
            ViewData["Path"] = _inputParser.Path;

            return View();
        }
    }
}

Controllers/WeatherModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Uppgift7.Data;
using Uppgift7.Models;

namespace Uppgift7.Controllers
{
    public class WeatherModelsController : Controller
    {
        private readonly MvcWeatherContext _context;
        private readonly IEnumerable<IWeatherData> _weatherAnalyticServices;

        public WeatherModelsController(MvcWeatherContext context, IEnumerable<IWeatherData> weatherAnalyticServices)
        {
            _context = context;
            _weatherAnalyticServices = weatherAnalyticServices;
        }

        // GET: WeatherModels
        public async Task<IActionResult> Index()
        {
            var weather = from w in _context.Weather
                          select w;
            foreach (var service in _weatherAnalyticServices)
            {
                weather = service.QueryData(weather);
            }
            return View(await weather.OrderBy(d => d.Timestamp).ToListAsync());
        }

        // GET: WeatherModels
        public async Task<IActionResult> IndexSearched(double lower, double upper)
        {
            var weather = from w in _context.Weather
                          select w;
            if (!(lower == 0 && upper == 0))
            {
                weather = weather.Where(t => t.Date.Hour >= lower && t.Date.Hour < upper);
            }
            weather = weather.OrderBy(w => w.Timestamp);
            foreach (var service in _weatherAnalyticServices)
            {
                weather = service.QueryData(weather);
            }
            return View(await weather.ToListAsync());
            //return View(await _context.Weather.ToListAsync());
        }

        // GET: WeatherModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var weatherModel = await _context.Weather
                .FirstOrDefaultAsync(m => m.Id == id);
            if (weatherModel == null)
            {
                return NotFound();
            }

            return View(weatherModel);
        }

        // GET: WeatherModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: WeatherModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Identifier,Timestamp,Date,TemperatureC")] WeatherModel weatherModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(weatherModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(weatherModel);
        }

        // GET: WeatherModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var weatherModel = await _context.Weather.FindAsync(id);
            if (weatherModel == null)
            {
                return NotFound();
            }
            return View(weatherModel);
        }

        // POST: WeatherModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Identifier,Timestamp,Date,TemperatureC")] WeatherModel weatherModel)
        {
            if (id != weatherModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(weatherModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WeatherModelExists(weatherModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(weatherModel);
        }

        // GET: WeatherModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var weatherModel = await _context.Weather
                .FirstOrDefaultAsync(m => m.Id == id);
            if (weatherModel == null)
            {
                return NotFound();
            }

            return View(weatherModel);
        }

        // POST: WeatherModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var weatherModel = await _context.Weather.FindAsync(id);
            _context.Weather.Remove(weatherModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WeatherModelExists(int id)
        {
            return _context.Weather.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Uppgift7</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="WeatherData" asp-action="Index">Uppgift7</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WeatherData" asp-action="Index">Weather Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WeatherModels" asp-action="Index">View Data</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Uppgift7 - <a asp-area="" asp-controller="WeatherData" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>